redis:
  endpoint: "telegram-bot-redis:6379"
open_ai:
  open_ai_base_url: "https://api.openai.com"
  conversation_idle_timeout_seconds: 5m
telegram:
  notify_user_on_conversation_idle_timeout: false
  is_not_public: true
  available_for_roles: [ "admin", "premium" ]
roles:
  - role: "admin"
    models: [ "gpt-3.5-turbo", "gpt-4.1", "gpt-4.1-mini", "gpt-4.1-nano", "gpt-4o", "gpt-4o-mini" ]
  - role: "premium"
    models: [ "gpt-3.5-turbo", "gpt-4.1", "gpt-4.1-mini", "gpt-4.1-nano", "gpt-4o", "gpt-4o-mini" ]
  - role: "default"
    models: [ "gpt-3.5-turbo" ]
