open_ai:
  open_ai_base_url: "https://api.openai.com"
  conversation_idle_timeout_seconds: 5m
telegram:
  notify_user_on_conversation_idle_timeout: false
  is_not_public: true
  available_for_roles: [ "admin", "premium" ]
